name: verify
on: [push, pull_request]
jobs:
  maven-verify:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.4
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      - name: Set up Workspace Enviroment Variable
        run: echo "WORKSPACE=${{ github.workspace }}" >> $GITHUB_ENV        
      - name: Build with Maven  within a virtual X Server Environment
        run: xvfb-run mvn clean verify checkstyle:check pmd:check pmd:cpd-check spotbugs:check -f ./ddk-parent/pom.xml --batch-mode --fail-at-end
      - name: Archive Tycho Surefire Plugin
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: tycho-surefire-plugin
          path: ${{ env.GITHUB_WORKSPACE }}/com.avaloq.tools.ddk.xtext.test/target/work/data/.metadata/.log
